"""
Patient Advocate — HITL FastAPI Router
=======================================

Exposes four HTTP endpoints for the Human-in-the-Loop decision gate:

  POST /hitl/decision          Submit an APPROVED / REJECTED / DEFERRED decision.
  POST /hitl/register          Push a new suggestion into the pending queue.
  GET  /hitl/pending/{patient_id}   List all pending suggestions for a patient.
  GET  /hitl/suggestion/{id}/status Query the lifecycle status of a suggestion.

Dependency injection:
  Each endpoint receives a ``HITLService`` instance via FastAPI's ``Depends``
  system.  The *actual* singleton is wired in ``app.py`` through dependency
  overrides; the placeholder here (``_get_hitl_service``) is intentionally
  a ``NotImplementedError`` so misconfigured deployments fail loudly at the
  first request rather than silently misbehaving.

HTTP status mapping:
  200  – Happy path.
  404  – Suggestion not found *or* wrong patient (HIPAA).
  409  – Terminal decision already recorded and cannot be overridden.
  422  – Pydantic validation failure (auto-generated by FastAPI).
  408  – HITL timeout — suggestion auto-deferred.
  500  – Audit write failure (Glass Box violation — always surfaced).

Author: Patient Advocate Platform Team
License: Apache-2.0
"""

from __future__ import annotations

import logging
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, status

from patient_advocate.api.hitl_service import HITLService
from patient_advocate.api.schemas import (
    HITLDecisionRequest,
    HITLDecisionResponse,
    PendingListResponse,
    SuggestionPayload,
    SuggestionStatusResponse,
)
from patient_advocate.core.exceptions import (
    AuditWriteError,
    HITLRejectionError,
    HITLTimeoutError,
)
from patient_advocate.core.models import HITLDecision

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/hitl", tags=["hitl"])


# ---------------------------------------------------------------------------
# Dependency placeholder — overridden by app.py at startup
# ---------------------------------------------------------------------------

def _get_hitl_service() -> HITLService:  # pragma: no cover
    raise NotImplementedError(
        "HITLService dependency has not been configured. "
        "Ensure create_app() wires the dependency override before serving."
    )


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------


@router.post(
    "/decision",
    response_model=HITLDecisionResponse,
    summary="Submit a HITL decision on a pending suggestion",
    responses={
        404: {"description": "Suggestion not found or wrong patient (HIPAA)"},
        408: {"description": "Review window expired; suggestion auto-deferred"},
        409: {"description": "Terminal decision already recorded"},
        500: {"description": "Audit write failure"},
    },
)
async def post_decision(
    request: HITLDecisionRequest,
    service: HITLService = Depends(_get_hitl_service),
) -> HITLDecisionResponse:
    """
    Submit an APPROVED, REJECTED, or DEFERRED decision for a pending suggestion.

    HIPAA note: wrong-patient requests return 404, *not* 403, to avoid
    confirming that a suggestion exists for another patient.
    """
    try:
        return await service.process_decision(request)
    except HITLRejectionError:
        # Decision was recorded successfully; surface as 200 with the response
        # that was built before the rejection error was raised.
        # Re-fetch from store to build response (service raised after mark_decided).
        decision_obj = await service._store.get_decision(request.suggestion_id)
        return HITLDecisionResponse(
            suggestion_id=request.suggestion_id,
            decision=decision_obj or HITLDecision.REJECTED,
            acknowledged=True,
        )
    except KeyError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=str(exc))
    except HITLTimeoutError as exc:
        raise HTTPException(
            status_code=status.HTTP_408_REQUEST_TIMEOUT, detail=str(exc)
        )
    except ValueError as exc:
        # Terminal decision override attempt.
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail=str(exc))
    except AuditWriteError as exc:
        logger.error("Audit write failure: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Audit record could not be written. Request aborted.",
        )


@router.post(
    "/register",
    summary="Register a new scheduling suggestion for HITL review",
    status_code=status.HTTP_201_CREATED,
)
async def post_register(
    payload: SuggestionPayload,
    service: HITLService = Depends(_get_hitl_service),
) -> dict:
    """
    Push a new scheduling suggestion into the HITL pending queue.

    Called by the Calendar Intelligence Engine after generating a suggestion
    that requires patient or case-manager review.  Idempotent: registering
    the same ``suggestion_id`` twice is a no-op.
    """
    await service.register_suggestion(payload)
    logger.info("Registered suggestion %s for patient %s", payload.suggestion_id, payload.patient_id)
    return {"registered": True}


@router.get(
    "/pending/{patient_id}",
    response_model=PendingListResponse,
    summary="List all pending suggestions for a patient",
)
async def get_pending(
    patient_id: UUID,
    service: HITLService = Depends(_get_hitl_service),
) -> PendingListResponse:
    """
    Return all suggestions that are still awaiting a decision for ``patient_id``.

    Timed-out suggestions are NOT automatically evicted by this endpoint;
    the background eviction task handles cleanup.  Callers should check
    ``/hitl/suggestion/{id}/status`` for individual timeout state.
    """
    pending = await service._store.get_pending_for_patient(patient_id)
    return PendingListResponse(patient_id=patient_id, pending=pending)


@router.get(
    "/suggestion/{suggestion_id}/status",
    response_model=SuggestionStatusResponse,
    summary="Query the lifecycle status of a suggestion",
    responses={
        404: {"description": "Suggestion not found"},
    },
)
async def get_suggestion_status(
    suggestion_id: UUID,
    service: HITLService = Depends(_get_hitl_service),
) -> SuggestionStatusResponse:
    """
    Return the current lifecycle status of a suggestion.

    Possible status values: ``pending``, ``approved``, ``rejected``,
    ``deferred``, ``timed_out``.
    """
    from patient_advocate.core.config import Settings

    payload = await service._store.get(suggestion_id)
    if payload is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Suggestion {suggestion_id} not found",
        )

    decision = await service._store.get_decision(suggestion_id)
    if decision is not None:
        status_str = decision.value
    else:
        # Check timeout inline (re-uses the same logic as process_decision)
        timed_out = await service._store.is_timed_out(suggestion_id, service._timeout)
        status_str = "timed_out" if timed_out else "pending"

    return SuggestionStatusResponse(suggestion_id=suggestion_id, status=status_str)
